# Generated by Django 4.1.7 on 2023-04-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_id_alter_todo_id_deletednote'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletednote',
            name='created',
            field=models.DateTimeField(null=True),
        ),
    ]
